using System.Globalization;
using System.Linq;
using BlazorCompose.Compiler.Diagnostics;
using Microsoft.CodeAnalysis;

namespace BlazorCompose.Compiler.Tests;

public sealed class GeneratorTests
{
    // The canonical counter component used to verify generator output.
    private const string PartialCounterSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class Counter : ComposeComponentBase
        {
            protected override View Body => Text("Count");
        }
        """;

    private const string VStackCounterSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class Counter : ComposeComponentBase
        {
            private int _count = 0;

            protected override View Body =>
                VStack(
                    Text($"Count: {_count}"),
                    Button("Increment", () => _count++));
        }
        """;

    private const string NestedPartialCounterSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class Outer
        {
            public partial class Counter : ComposeComponentBase
            {
                protected override View Body => Text("Count");
            }
        }
        """;

    private const string BlockBodySource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class Counter : ComposeComponentBase
        {
            protected override View Body
            {
                get { return Text("Count"); }
            }
        }
        """;

    private const string UnrecognizedChildSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class Counter : ComposeComponentBase
        {
            private View GetView() => Text("foo");

            protected override View Body =>
                VStack(GetView());
        }
        """;

    [Fact]
    public void Generator_PartialComponent_EmitsRenderBody()
    {
        var result = CompilationTestHost.RunGenerator(PartialCounterSource);

        var source = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.Contains(
            "protected override void RenderBody(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)",
            source);
        Assert.Contains("__builder.OpenElement(0, \"span\")", source);
        Assert.Contains("__builder.AddContent(1, \"Count\")", source);
    }

    [Fact]
    public void Generator_VStackWithTextAndButton_EmitsLinearSscRenderBody()
    {
        var result = CompilationTestHost.RunGenerator(VStackCounterSource);

        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // Sequence-literal builder calls in preorder
        Assert.Contains("__builder.OpenElement(0, \"div\")", generated);
        Assert.Contains("__builder.OpenElement(1, \"span\")", generated);
        Assert.Contains("__builder.AddContent(2, $\"Count: {_count}\")", generated);
        Assert.Contains("__builder.OpenElement(3, \"button\")", generated);
        Assert.Contains(
            "__builder.AddAttribute(4, \"onclick\", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, () => _count++))",
            generated);
        Assert.Contains("__builder.AddContent(5, \"Increment\")", generated);

        // No runtime Body access, no runtime sequence variable
        Assert.DoesNotContain(".Body", generated);
        Assert.DoesNotContain("get_Body", generated);
    }

    [Fact]
    public void Generator_VStackCounter_EmitsExactSource()
    {
        // Golden test: locks the full generated-source shape — indentation, blank lines, brace
        // placement, and preorder sequence — that the substring assertions elsewhere do not cover,
        // guarding the RenderBodyEmitter's exact output. Line endings are normalized to '\n' because
        // the emitter uses Environment.NewLine (platform-dependent); structure must stay identical.
        var result = CompilationTestHost.RunGenerator(VStackCounterSource);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString()
            .Replace("\r\n", "\n");

        const string expected = """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0219

            partial class Counter
            {
                protected override void RenderBody(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
                {
                    __builder.OpenElement(0, "div");
                    __builder.OpenElement(1, "span");
                    __builder.AddContent(2, $"Count: {_count}");
                    __builder.CloseElement();
                    __builder.OpenElement(3, "button");
                    __builder.AddAttribute(4, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, () => _count++));
                    __builder.AddContent(5, "Increment");
                    __builder.CloseElement();
                    __builder.CloseElement();
                }
            }
            """;

        Assert.Equal(expected, generated);
    }

    [Fact]
    public async Task Generator_NestedPartialComponent_EmitsNoSourceAndReportsCS0534()
    {
        var result = CompilationTestHost.RunGenerator(NestedPartialCounterSource);

        Assert.Empty(result.GeneratedSources);

        var analyzerDiagnostics = await CompilationTestHost.RunAnalyzerAsync<PartialComponentAnalyzer>(NestedPartialCounterSource);
        Assert.DoesNotContain(analyzerDiagnostics, static diagnostic => diagnostic.Id == "BC1001");

        var diagnostic = Assert.Single(
            result.OutputCompilation.GetDiagnostics(), static diagnostic => diagnostic.Id == "CS0534");

        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("Outer.Counter", diagnostic.GetMessage(CultureInfo.InvariantCulture));
    }

    [Fact]
    public void Generator_BlockBody_EmitsNoSourceAndReportsCS0534()
    {
        var result = CompilationTestHost.RunGenerator(BlockBodySource);

        Assert.Empty(result.GeneratedSources);
        Assert.Single(result.OutputCompilation.GetDiagnostics(), static d => d.Id == "CS0534");
    }

    [Fact]
    public void Generator_UnrecognizedChild_EmitsNoSourceAndReportsCS0534()
    {
        var result = CompilationTestHost.RunGenerator(UnrecognizedChildSource);

        Assert.Empty(result.GeneratedSources);
        Assert.Single(result.OutputCompilation.GetDiagnostics(), static d => d.Id == "CS0534");
    }

    // -----------------------------------------------------------------------
    // If emission
    // -----------------------------------------------------------------------

    private const string IfCounterSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class IfCounter : ComposeComponentBase
        {
            private bool _visible = true;

            protected override View Body =>
                VStack(
                    If(_visible, () => Text("Yes"), () => Text("No")),
                    Text("Always"));
        }
        """;

    [Fact]
    public void Generator_IfWithBothBranches_EmitsDisjointSequenceRangesAndStableFollowingSequence()
    {
        var result = CompilationTestHost.RunGenerator(IfCounterSource);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // VStack outer element at 0
        Assert.Contains("__builder.OpenElement(0, \"div\")", generated);

        // If region boundary at 1 (one literal sequence for the conditional region)
        Assert.Contains("__builder.OpenRegion(1)", generated);

        // then branch: Text("Yes") uses [2, 3]
        Assert.Contains("__builder.OpenElement(2, \"span\")", generated);
        Assert.Contains("__builder.AddContent(3, \"Yes\")", generated);

        // else branch: Text("No") uses [4, 5] — disjoint from then range [2, 3]
        Assert.Contains("__builder.OpenElement(4, \"span\")", generated);
        Assert.Contains("__builder.AddContent(5, \"No\")", generated);

        // Region close (no sequence argument)
        Assert.Contains("__builder.CloseRegion()", generated);

        // Text("Always") starts at 6 — same sequence regardless of which branch ran
        Assert.Contains("__builder.OpenElement(6, \"span\")", generated);
        Assert.Contains("__builder.AddContent(7, \"Always\")", generated);

        // All sequence numbers are compile-time literals; no runtime ++ variable
        Assert.DoesNotContain("__seq", generated);
        Assert.DoesNotContain("seqVar", generated);
    }

    private const string IfOnlyThenSource = """
        using BlazorCompose;
        using static BlazorCompose.UI;

        public partial class IfThen : ComposeComponentBase
        {
            private bool _show = true;

            protected override View Body =>
                If(_show, () => Text("Visible"), null);
        }
        """;

    [Fact]
    public void Generator_IfWithNullOtherwise_EmitsThenBranchOnly()
    {
        var result = CompilationTestHost.RunGenerator(IfOnlyThenSource);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("__builder.OpenRegion(0)", generated);
        Assert.Contains("__builder.OpenElement(1, \"span\")", generated);
        Assert.Contains("__builder.AddContent(2, \"Visible\")", generated);
        Assert.Contains("__builder.CloseRegion()", generated);

        // No else branch
        Assert.DoesNotContain("else", generated);
    }

    private const string ForEachComponentSource = """
        using System.Collections.Generic;
        using static BlazorCompose.UI;

        public partial class TodoPage : BlazorCompose.ComposeComponentBase
        {
            private readonly List<Todo> _items = new();

            protected override BlazorCompose.View Body =>
                VStack(
                    ForEach(_items, key: t => t.Id, content: item => Text(item.Title)),
                    Text("footer"));

            private sealed record Todo(int Id, string Title);
        }
        """;

    [Fact]
    public void Generator_ForEachOverItems_EmitsKeyedForeachRegionWithStableFollowingSequence()
    {
        var result = CompilationTestHost.RunGenerator(ForEachComponentSource);

        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // VStack opens at 0; ForEach region at 1; content Text spans seq 2..3; SetKey consumes none.
        Assert.Contains("__builder.OpenElement(0, \"div\");", generated);
        Assert.Contains("__builder.OpenRegion(1);", generated);
        Assert.Contains("foreach (var __bc_item_", generated);
        Assert.Contains(" in _items)", generated);
        Assert.Contains(".Id);", generated);       // SetKey uses the item
        Assert.Contains(".Title);", generated);    // content uses the item
        Assert.Contains("__builder.OpenElement(2, \"span\");", generated);
        Assert.Contains("__builder.AddContent(3,", generated);
        Assert.Contains("__builder.CloseRegion();", generated);
        // Following sibling is stable: VStack(1) + ForEach region(1 + content 2) => next span at 4.
        Assert.Contains("__builder.OpenElement(4, \"span\");", generated);
        Assert.Contains("__builder.AddContent(5, \"footer\");", generated);

        // SetKey must land on the content root's span frame — after OpenElement(2, "span"), never
        // after OpenRegion(1). This is the regression guard for the Task-9 render-time defect.
        int spanIdx = generated.IndexOf("__builder.OpenElement(2, \"span\");", System.StringComparison.Ordinal);
        int keyIdx = generated.IndexOf("__builder.SetKey(", System.StringComparison.Ordinal);
        Assert.True(spanIdx >= 0, "content root OpenElement should be emitted");
        Assert.True(keyIdx > spanIdx, "SetKey must be emitted after the content root's OpenElement");

        CompilationTestHost.AssertOutputCompiles(result);
    }

    private const string NestedForEachInComposableSource = """
        using System.Collections.Generic;
        using static BlazorCompose.UI;

        public partial class BoardPage : BlazorCompose.ComposeComponentBase
        {
            private readonly List<Column> _columns = new();

            protected override BlazorCompose.View Body => Section("Board", _columns);

            [BlazorCompose.Composable]
            private static BlazorCompose.View Section(string heading, List<Column> columns) =>
                VStack(
                    Text(heading),
                    ForEach(columns, key: col => col.Id, content: col =>
                        VStack(ForEach(col.Cards, key: card => card.Id, content: card =>
                            Text($"{heading}:{col.Name}:{card.Title}")))));

            public sealed record Card(int Id, string Title);
            public sealed record Column(int Id, string Name, List<Card> Cards);
        }
        """;

    [Fact]
    public void Generator_NestedForEachInComposable_BindsOuterParamOuterItemAndInnerItemToDistinctLocals()
    {
        var result = CompilationTestHost.RunGenerator(NestedForEachInComposableSource);

        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // Two distinct loop variables, distinct from the composable arg locals.
        Assert.Contains("foreach (var __bc_item_", generated);
        // The innermost interpolation references the composable parameter (heading -> __bc_arg local),
        // the outer item (col), and the inner item (card) — all resolved, and the output compiles.
        CompilationTestHost.AssertOutputCompiles(result);
        // No BC3002 (every key references its own item).
        Assert.DoesNotContain(result.Diagnostics, d => d.Id == "BC3002");
        // No BC3003: the outer content root is now a VStack (div), a keyable element frame.
        Assert.DoesNotContain(result.Diagnostics, d => d.Id == "BC3003");
    }

    [Fact]
    public void Generator_ForEachWithRegionRootedContent_ReportsBC3003()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<Group> _groups = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_groups, key: g => g.Id, content: g =>
                        ForEach(g.Items, key: i => i.Id, content: i => Text(i.Name)));
                private sealed record Item(int Id, string Name);
                private sealed record Group(int Id, List<Item> Items);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // The outer content root is a bare nested ForEach (region-rooted) — its key has no frame to
        // attach to, so BC3003 fires and emission is suppressed.
        Assert.Contains(result.Diagnostics, d => d.Id == "BC3003" && d.Severity == DiagnosticSeverity.Error);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_RegionRootedContentComposableCalledTwice_ReportsBC3003Once()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<Group> _a = new();
                private readonly List<Group> _b = new();
                protected override BlazorCompose.View Body =>
                    VStack(Widget(_a), Widget(_b));
                [BlazorCompose.Composable]
                private static BlazorCompose.View Widget(List<Group> gs) =>
                    ForEach(gs, key: g => g.Id, content: g =>
                        ForEach(g.Items, key: i => i.Id, content: i => Text(i.Name)));
                private sealed record Item(int Id, string Name);
                private sealed record Group(int Id, List<Item> Items);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // Reported once (dedup across the two call sites), and both paths agree: BC3003 fires AND emission
        // is suppressed (guards resolver/expander keyability from drifting apart).
        Assert.Single(result.Diagnostics, d => d.Id == "BC3003");
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ComponentForEachContentIsRegionRootedComposableCall_ReportsBC3003()
    {
        // Case B: the bad ForEach is in the COMPONENT body; its content is a composable call whose body is
        // region-rooted. Transitive root-kind resolution (registry) must detect this from the component side.
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<Group> _groups = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_groups, key: g => g.Id, content: g => Rows(g));
                [BlazorCompose.Composable]
                private static BlazorCompose.View Rows(Group g) =>
                    ForEach(g.Items, key: i => i.Id, content: i => Text(i.Name));
                private sealed record Item(int Id, string Name);
                private sealed record Group(int Id, List<Item> Items);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.Contains(result.Diagnostics, d => d.Id == "BC3003" && d.Severity == DiagnosticSeverity.Error);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_RegionRootedContentInUncalledComposable_StillReportsBC3003()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public static class Widgets
            {
                [BlazorCompose.Composable]
                public static BlazorCompose.View Never(List<Group> gs) =>
                    ForEach(gs, key: g => g.Id, content: g =>
                        ForEach(g.Items, key: i => i.Id, content: i => Text(i.Name)));
                public sealed record Item(int Id, string Name);
                public sealed record Group(int Id, List<Item> Items);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.Single(result.Diagnostics, d => d.Id == "BC3003");
    }

    [Fact]
    public void Generator_ForEachAcceptsSimpleParenthesizedAndTypedLambdas_AllCompile()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;

            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<int> _xs = new();
                protected override BlazorCompose.View Body =>
                    VStack(
                        ForEach(_xs, key: x => x, content: x => Text(x.ToString())),
                        ForEach(_xs, key: (x) => x, content: (x) => Text(x.ToString())),
                        ForEach(_xs, key: (int x) => x, content: (int x) => Text(x.ToString())));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.Single(result.GeneratedSources);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ForEachConstantKey_ReportsBC3002()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<int> _xs = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_xs, key: _ => 0, content: x => Text(x.ToString()));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.Contains(result.Diagnostics, d => d.Id == "BC3002" && d.Severity == DiagnosticSeverity.Warning);
        // A warning must not suppress emission.
        Assert.Single(result.GeneratedSources);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ForEachItemDerivedKey_DoesNotReportBC3002()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<Row> _xs = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_xs, key: r => r.Id, content: r => Text(r.Name));
                private sealed record Row(int Id, string Name);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.DoesNotContain(result.Diagnostics, d => d.Id == "BC3002");
    }

    [Fact]
    public void Generator_NestedForEachInnerKeyReferencesOnlyOuterItem_ReportsBC3002()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<Group> _groups = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_groups, key: g => g.Id, content: g =>
                        VStack(ForEach(g.Items, key: i => g.Id, content: i => Text(i.Name))));
                private sealed record Item(int Id, string Name);
                private sealed record Group(int Id, List<Item> Items);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // Exactly one BC3002 — the inner key references only the outer item, not its own.
        Assert.Single(result.Diagnostics, d => d.Id == "BC3002");
    }

    [Fact]
    public void Generator_BadKeyForEachInComposableCalledTwice_ReportsBC3002Once()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<int> _xs = new();
                protected override BlazorCompose.View Body => VStack(Widget(_xs), Widget(_xs));
                [BlazorCompose.Composable]
                private static BlazorCompose.View Widget(List<int> xs) =>
                    ForEach(xs, key: _ => 0, content: x => Text(x.ToString()));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.Single(result.Diagnostics, d => d.Id == "BC3002");
    }

    [Fact]
    public void Generator_BadKeyForEachInUnreachableComposable_StillReportsBC3002()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public static class Widgets
            {
                [BlazorCompose.Composable]
                public static BlazorCompose.View Never(List<int> xs) =>
                    ForEach(xs, key: _ => 0, content: x => Text(x.ToString()));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // Reported at definition-discovery time, independent of any call site.
        Assert.Single(result.Diagnostics, d => d.Id == "BC3002");
    }

    [Fact]
    public void Generator_ForEachWithMethodGroupContent_ProducesNoSourceWithoutCrashing()
    {
        const string source = """
            using System.Collections.Generic;
            using static BlazorCompose.UI;
            public partial class P : BlazorCompose.ComposeComponentBase
            {
                private readonly List<int> _xs = new();
                protected override BlazorCompose.View Body =>
                    ForEach(_xs, key: x => x, content: Render);
                private static BlazorCompose.View Render(int x) => Text(x.ToString());
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // Non-SSC content (method group, not an inline lambda): no generated RenderBody, no exception.
        Assert.Empty(result.GeneratedSources);
    }

    // -----------------------------------------------------------------------
    // Static composable call-site expansion
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_StaticComposable_ExpandsWithoutRuntimeMethodCall()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Label(string value) => Text(value);

                private string Compute() => "Count";

                protected override View Body =>
                    VStack(Label(Compute()), Text("After"));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("string __bc_arg_1_0 = Compute();", generated);
        Assert.Contains("__builder.OpenElement(1, \"span\")", generated);
        Assert.Contains("__builder.AddContent(2, __bc_arg_1_0)", generated);
        Assert.Contains("__builder.OpenElement(3, \"span\")", generated);
        Assert.DoesNotContain("Label(", generated);
    }

    [Fact]
    public void Generator_SameComposableCalledTwice_UsesDistinctLocalsAndSequences()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Label(string value) => Text(value);

                protected override View Body =>
                    VStack(Label("A"), Label("B"));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // Distinct locals from distinct logical preorder ordinals (Label calls are 1 and 3).
        Assert.Contains("string __bc_arg_1_0 = \"A\";", generated);
        Assert.Contains("string __bc_arg_3_0 = \"B\";", generated);

        // Disjoint runtime sequence ranges for the two expanded Text nodes.
        Assert.Contains("__builder.AddContent(2, __bc_arg_1_0)", generated);
        Assert.Contains("__builder.AddContent(4, __bc_arg_3_0)", generated);

        Assert.DoesNotContain("Label(", generated);
    }

    [Fact]
    public void Generator_NamedArguments_EmitInSourceOrderMappedToParameterOrdinals()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Pair(string first, string second) => Text(first + second);

                private string A() => "a";
                private string B() => "b";

                protected override View Body =>
                    Pair(second: B(), first: A());
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // Locals are named by parameter ordinal (first=0, second=1) but are emitted in source
        // evaluation order (second is written first in source).
        AssertAppearsBefore(generated, "__bc_arg_0_1 = B();", "__bc_arg_0_0 = A();");

        // The body maps holes back to their parameter ordinals.
        Assert.Contains("__builder.AddContent(1, __bc_arg_0_0 + __bc_arg_0_1)", generated);
    }

    [Fact]
    public void Generator_UnusedSuppliedArgument_StillReceivesLocal()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Ignore(string used, string unused) => Text(used);

                protected override View Body => Ignore("keep", "drop");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("string __bc_arg_0_0 = \"keep\";", generated);
        Assert.Contains("string __bc_arg_0_1 = \"drop\";", generated);
        Assert.Contains("__builder.AddContent(1, __bc_arg_0_0)", generated);
    }

    [Fact]
    public void Generator_GeneratedSource_DisablesCS0219AfterNullableDirective()
    {
        var result = CompilationTestHost.RunGenerator(PartialCounterSource);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The CS0219 pragma must follow the nullable directive and precede the generated declarations.
        AssertAppearsBefore(generated, "#nullable enable", "#pragma warning disable CS0219");
        AssertAppearsBefore(generated, "#pragma warning disable CS0219", "partial class Counter");
    }

    [Fact]
    public void Generator_UnusedConstantComposableArgument_KeepsLocalWithoutCS0219Diagnostic()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Ignore(string used, string unused) => Text(used);

                protected override View Body => Ignore("keep", "drop");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("string __bc_arg_0_0 = \"keep\";", generated);
        Assert.Contains("string __bc_arg_0_1 = \"drop\";", generated);
        Assert.DoesNotContain(
            result.OutputCompilation.GetDiagnostics(),
            static diagnostic => diagnostic.Id == "CS0219");
    }

    [Fact]
    public void Generator_LambdaAndMethodGroupArguments_ReceiveDelegateParameterType()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Clickable(string label, System.Action onClick) => Button(label, onClick);

                private void Handle() { }

                protected override View Body =>
                    VStack(
                        Clickable("lambda", () => Handle()),
                        Clickable("group", Handle));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The typed local gives the lambda and method group their exact delegate target type.
        Assert.Contains("global::System.Action __bc_arg_1_1 = () => Handle();", generated);
        Assert.Contains("global::System.Action __bc_arg_3_1 = Handle;", generated);
    }

    [Fact]
    public void Generator_NumericImplicitConversion_UsesDeclaredParameterType()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Sized(double width) => Text(width.ToString());

                protected override View Body => Sized(5);
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The declared parameter type (double) drives the implicit int-to-double conversion.
        Assert.Contains("double __bc_arg_0_0 = 5;", generated);
        Assert.Contains("__builder.AddContent(1, __bc_arg_0_0.ToString())", generated);
    }

    [Fact]
    public void Generator_ComposableCallInIfBranch_DeclaresLocalInsideBranchBraces()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                private bool _show = true;

                [Composable]
                private static View Label(string value) => Text(value);

                protected override View Body =>
                    If(_show, () => Label("in-branch"), () => Text("no"));
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The expansion local must be declared inside the then branch, before the else branch.
        AssertAppearsBefore(generated, "if (_show)", "__bc_arg_1_0 = \"in-branch\";");
        AssertAppearsBefore(generated, "__bc_arg_1_0 = \"in-branch\";", "else");
        Assert.DoesNotContain("Label(", generated);
    }

    [Fact]
    public void Generator_RecursiveComposableCycle_ReportsBC1002AndEmitsNoSource()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Ping() => Pong();

                [Composable]
                private static View Pong() => Ping();

                protected override View Body => Ping();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains("cycle", diagnostic.GetMessage(CultureInfo.InvariantCulture));
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_CallToInvalidComposable_ReportsOnlyDeclarationDiagnostic()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                // Invalid declaration: a composable must be static.  The call site must not add a
                // duplicate BC1002.
                [Composable]
                private View Helper() => Text("x");

                protected override View Body => Helper();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains("must be static", diagnostic.GetMessage(CultureInfo.InvariantCulture));
        Assert.Empty(result.GeneratedSources);
    }

    // -----------------------------------------------------------------------
    // Cross-file and definition-context normalization
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_CrossFileComposable_UsesDefinitionSemanticModel()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public static class Widgets
                {
                    internal const string Prefix = "Value: ";

                    [Composable]
                    public static View Label(string value) =>
                        Text(Prefix + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets.Label("1");
                }
                """));

        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.Contains("global::Widgets.Prefix", generated);
        Assert.DoesNotContain("Widgets.Label(", generated);
    }

    [Fact]
    public void Generator_PrivateCrossTypeMemberReference_ReportsBC1002AtCall()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public static class Widgets
                {
                    private static string Secret() => "s";

                    [Composable]
                    public static View Label(string value) => Text(Secret() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Secret", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ProtectedCrossTypeReference_IsValidatedAgainstInheritance()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract partial class WidgetBase : ComposeComponentBase
                {
                    protected static string Prefix() => "P:";

                    [Composable]
                    protected static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : WidgetBase
                {
                    protected override View Body => Label("x");
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var counter = Assert.Single(
            result.GeneratedSources, static s => s.HintName.Contains("Counter"));
        var generated = counter.SourceText.ToString();
        Assert.Contains("global::WidgetBase.Prefix", generated);
        Assert.DoesNotContain("Label(", generated);
    }

    [Fact]
    public void Generator_ProtectedCrossTypeReferenceFromUnrelatedComponent_ReportsBC1002AtCall()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract class WidgetBase
                {
                    protected static string Prefix() => "P:";

                    [Composable]
                    public static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => WidgetBase.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Prefix", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ProtectedInternalCrossTypeReference_IsAccessibleThroughInternalHalf()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract class WidgetBase
                {
                    protected internal static string Prefix() => "P:";

                    [Composable]
                    public static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => WidgetBase.Label("x");
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.Contains("global::WidgetBase.Prefix", generated);
        Assert.DoesNotContain("Label(", generated);
    }

    [Fact]
    public void Generator_PrivateProtectedCrossTypeReferenceFromUnrelatedComponent_ReportsBC1002AtCall()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract class WidgetBase
                {
                    private protected static string Prefix() => "P:";

                    [Composable]
                    public static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => WidgetBase.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Prefix", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_MetadataOnlyComposable_ReportsBC1002AtCall()
    {
        var libraryReference = CompilationTestHost.CompileToMetadataReference("""
            using BlazorCompose;
            using static BlazorCompose.UI;

            public static class ExternalWidgets
            {
                [Composable]
                public static View Badge(string text) => Text(text);
            }
            """,
            "ExternalWidgets");

        var compilation = CompilationTestHost.CreateCompilation(
            [
                ("Counter.cs", """
                    using BlazorCompose;
                    using static BlazorCompose.UI;

                    public partial class Counter : ComposeComponentBase
                    {
                        protected override View Body => ExternalWidgets.Badge("hi");
                    }
                    """),
            ],
            libraryReference);

        var result = CompilationTestHost.RunGenerator(compilation);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains("no source declaration", diagnostic.GetMessage(CultureInfo.InvariantCulture));
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_UnnameableParameterType_ReportsBC1002AndEmitsNoSource()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            file class Hidden { }

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Show(Hidden h) => Text("x");

                protected override View Body => Show(new Hidden());
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains("cannot be named", diagnostic.GetMessage(CultureInfo.InvariantCulture));
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_NestedComposableCalls_ExpandTransitively()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Inner(string value) => Text(value);

                [Composable]
                private static View Outer(string value) => VStack(Inner(value), Text("tail"));

                protected override View Body => Outer("hi");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.DoesNotContain("Outer(", generated);
        Assert.DoesNotContain("Inner(", generated);
        Assert.Contains("\"tail\"", generated);
    }

    [Fact]
    public void Generator_DirectRecursion_ReportsSingleBC1002()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Loop() => Loop();

                protected override View Body => Loop();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("cycle", message);
        Assert.Contains("Loop -> Loop", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_IndirectRecursion_ReportsSingleBC1002WithCallChain()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Ping() => Pong();

                [Composable]
                private static View Pong() => Ping();

                protected override View Body => Ping();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("cycle", message);
        Assert.Contains("Ping -> Pong -> Ping", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ParameterShadowingInsideNestedLambda_IsNotReplaced()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Echo(string value) =>
                    Text(((System.Func<string, string>)(value => value))(value));

                protected override View Body => Echo("hi");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The shadowing lambda parameter keeps its source name ...
        Assert.Contains("value => value", generated);
        // ... while the composable parameter reference becomes the typed local.
        Assert.Contains("__bc_arg_0_0", generated);
        Assert.DoesNotContain("Echo(", generated);
    }

    [Fact]
    public void Generator_NameofParameter_EmitsCompileTimeConstantString()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Named(string value) => Text(nameof(value));

                protected override View Body => Named("x");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The parameter 'value' does not exist after expansion, so nameof(value) must collapse to its
        // compile-time constant string rather than reference an out-of-scope name.
        Assert.Contains("__builder.AddContent(1, \"value\")", generated);
        Assert.DoesNotContain("nameof(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_NameofParameterMember_EmitsMemberNameConstant()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View NamedMember(string value) => Text(nameof(value.Length));

                protected override View Body => NamedMember("x");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // nameof(value.Length) evaluates to "Length"; the vanished parameter must not survive as text.
        Assert.Contains("__builder.AddContent(1, \"Length\")", generated);
        Assert.DoesNotContain("value", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_NameofNonParameter_CollapsesToCompileTimeConstantString()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View NamedType(string value) => Text(nameof(System.String) + value);

                protected override View Body => NamedType("x");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // Every nameof collapses to its compile-time constant string; nameof(System.String) is "String".
        Assert.Contains("\"String\" + __bc_arg_0_0", generated);
        Assert.DoesNotContain("nameof(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_NameofUsingImportedType_CollapsesToConstantAndCompiles()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using System.Text;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Named() => Text(nameof(StringBuilder));

                protected override View Body => Named();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // 'StringBuilder' is only in scope through 'using System.Text;', which the generated file lacks;
        // the nameof must collapse to its constant string rather than reference an out-of-scope type.
        Assert.Contains("__builder.AddContent(1, \"StringBuilder\")", generated);
        Assert.DoesNotContain("nameof(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_NameofPrivateDefinitionMember_CollapsesToConstantAndCompiles()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public static class Widgets
                {
                    private static readonly string _secret = "s";

                    // Referenced so the private field is not reported as unused; the composable itself
                    // only names it through nameof.
                    public static string Reveal() => _secret;

                    [Composable]
                    public static View Show() => Text(nameof(_secret));
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets.Show();
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // '_secret' is a private field of Widgets and does not exist inside Counter's generated RenderBody;
        // nameof(_secret) must collapse to its constant string so it never references the vanished member.
        Assert.Contains("__builder.AddContent(1, \"_secret\")", generated);
        Assert.DoesNotContain("nameof(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_InterpolatedParameterReference_IsReplaced()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Greet(string value) => Text($"Hi {value}!");

                protected override View Body => Greet("x");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("$\"Hi {__bc_arg_0_0}!\"", generated);
    }

    [Fact]
    public void Generator_OptionalEnumDefault_IsFullyQualified()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public enum Color { Red, Green }

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Swatch(Color c = Color.Green) => Text(c.ToString());

                protected override View Body => Swatch();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("global::Color __bc_arg_0_0 = (global::Color)1;", generated);
    }

    [Fact]
    public void Generator_OptionalValueTypeDefault_EmitsDefaultOfFullyQualifiedType()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public struct Box { public int V; }

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Show(Box b = default) => Text(b.V.ToString());

                protected override View Body => Show();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("global::Box __bc_arg_0_0 = default(global::Box);", generated);
    }

    // -----------------------------------------------------------------------
    // Fractional and special floating-point / decimal optional defaults
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_OptionalSingleDefault_EmitsFloatSuffixedLiteral()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Scaled(float scale = 1.5f) => Text(scale.ToString());

                protected override View Body => Scaled();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // A bare 1.5 is a double literal and cannot initialize a float local (CS0664); the 'F' suffix
        // makes the constant round-trip into the declared parameter type.
        Assert.Contains("float __bc_arg_0_0 = 1.5F;", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_OptionalDecimalDefault_EmitsDecimalSuffixedLiteral()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Priced(decimal amount = 1.5m) => Text(amount.ToString());

                protected override View Body => Priced();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // A bare 1.5 is a double literal and cannot initialize a decimal local (CS0664); the 'M' suffix
        // makes the constant round-trip into the declared parameter type.
        Assert.Contains("decimal __bc_arg_0_0 = 1.5M;", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_OptionalSpecialFloatingPointDefaults_EmitTypedConstants()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Special(
                    float f = float.NaN,
                    double d = double.PositiveInfinity,
                    double n = double.NegativeInfinity) =>
                    Text(f.ToString() + d.ToString() + n.ToString());

                protected override View Body => Special();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        Assert.Contains("float __bc_arg_0_0 = float.NaN;", generated);
        Assert.Contains("double __bc_arg_0_1 = double.PositiveInfinity;", generated);
        Assert.Contains("double __bc_arg_0_2 = double.NegativeInfinity;", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    // -----------------------------------------------------------------------
    // Accessibility of member-access (qualified) non-public references
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_PrivateMemberAccessReferenceFromUnrelatedComponent_ReportsBC1002AtCall()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public static class Widgets
                {
                    private static string Secret() => "s";

                    // Qualified member access to a private member: legal here, but inaccessible once
                    // inlined into an unrelated component.
                    [Composable]
                    public static View Label(string value) => Text(Widgets.Secret() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Secret", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ProtectedMemberAccessReferenceFromUnrelatedComponent_ReportsBC1002AtCall()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract class WidgetBase
                {
                    protected static string Prefix() => "P:";

                    [Composable]
                    public static View Label(string value) => Text(WidgetBase.Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => WidgetBase.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Prefix", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_PrivateMemberAccessReferenceFromSameType_ExpandsAndCompiles()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Widget : ComposeComponentBase
            {
                private static string Secret() => "s";

                [Composable]
                private static View Label(string value) => Text(Widget.Secret() + value);

                protected override View Body => Label("x");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.Contains("global::Widget.Secret()", generated);
        Assert.DoesNotContain("Label(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ProtectedMemberAccessReferenceFromDerivedComponent_ExpandsAndCompiles()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract partial class WidgetBase : ComposeComponentBase
                {
                    protected static string Prefix() => "P:";

                    [Composable]
                    protected static View Label(string value) => Text(WidgetBase.Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : WidgetBase
                {
                    protected override View Body => Label("x");
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var counter = Assert.Single(
            result.GeneratedSources, static s => s.HintName.Contains("Counter"));
        var generated = counter.SourceText.ToString();
        Assert.Contains("global::WidgetBase.Prefix()", generated);
        Assert.DoesNotContain("Label(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    // -----------------------------------------------------------------------
    // Using-dependent qualification: generic type/static references and
    // extension methods invoked in instance syntax
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_ComposableGenericTypeAndExtensionMethod_QualifyInUsinglessOutput()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using System.Collections.Generic;
            using System.Linq;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Head(IEnumerable<string> items) => Text(items.First());

                protected override View Body => Head(new List<string> { "a" });
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The 'items.First()' extension call, only in scope through 'using System.Linq;', normalizes to a
        // fully qualified static call, and the generic 'List<string>' argument is fully qualified.
        Assert.Contains("global::System.Linq.Enumerable.First", generated);
        Assert.Contains(
            "global::System.Collections.Generic.IEnumerable<string> __bc_arg_0_0 = " +
            "new global::System.Collections.Generic.List<string> { \"a\" };",
            generated);
        Assert.DoesNotContain(".First()", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ComposableUnqualifiedGenericStaticMethodAndGenericType_QualifyInUsinglessOutput()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using static Factory;
            using System.Collections.Generic;

            public static class Factory
            {
                public static string Make<T>() => typeof(T).Name;
            }

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Head() =>
                    Text(Make<string>() + new Dictionary<string, int>().Count.ToString());

                protected override View Body => Head();
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The unqualified generic static call and generic type reference — both in scope only through
        // 'using' directives the generated file lacks — are fully qualified while preserving type arguments.
        Assert.Contains("global::Factory.Make<string>()", generated);
        Assert.Contains("global::System.Collections.Generic.Dictionary<string, int>", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ComponentBodyGenericTypeAndExtensionMethod_QualifyAndCompile()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using System.Collections.Generic;
            using System.Linq;

            public partial class Counter : ComposeComponentBase
            {
                protected override View Body => Text((new List<string> { "a" }).First());
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The shared analyzer also serves component Body expressions, so the same using-dependent generic
        // type and instance-syntax extension call must qualify and compile there too.
        Assert.Contains("global::System.Linq.Enumerable.First", generated);
        Assert.Contains("new global::System.Collections.Generic.List<string> { \"a\" }", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ComposableExtensionMethodWithUnnameableTypeArgument_ReportsBC1002()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using System.Collections.Generic;
            using System.Linq;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Head(IEnumerable<string> items) =>
                    Text(items.Select(x => new { N = x }).First().N);

                protected override View Body => Head(new List<string> { "a" });
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // The reduced 'Select' fixes an anonymous type argument that cannot be named in generated component
        // code, so normalization is not semantics-preserving and a precise BC1002 is reported instead.
        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("cannot be named", message);
        Assert.Empty(result.GeneratedSources);
    }

    // -----------------------------------------------------------------------
    // By-reference [Composable] parameters (ref / out / in / ref readonly)
    // -----------------------------------------------------------------------

    [Theory]
    [InlineData("ref int value")]
    [InlineData("out int value")]
    [InlineData("in int value")]
    [InlineData("ref readonly int value")]
    public void Generator_ByReferenceComposableParameter_ReportsBC1002AndEmitsNoInvalidOutput(string parameter)
    {
        var source = $$"""
            using BlazorCompose;
            using static BlazorCompose.UI;

            public partial class Counter : ComposeComponentBase
            {
                [Composable]
                private static View Helper({{parameter}}) => Text("x");

                protected override View Body => Text("Body");
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // A by-reference parameter rejects the declaration with exactly one BC1002 and one reason.
        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains(
            "by-reference parameters are unsupported",
            diagnostic.GetMessage(CultureInfo.InvariantCulture));

        // The rejected composable is never expanded, so the component's own valid Body still emits
        // while nothing references the invalid Helper: no broken generated output is produced.
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();
        Assert.DoesNotContain("Helper", generated);
        Assert.Contains("\"Body\"", generated);
    }

    // -----------------------------------------------------------------------
    // Namespace-relative type / static references qualify across namespaces
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_CrossNamespaceRelativeTypeReference_QualifiesAndCompiles()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                namespace Root.Models
                {
                    public sealed class Widget
                    {
                        public static string Label => "widget";
                    }

                    public sealed class Box<T>
                    {
                        public static string Describe => typeof(T).Name;
                    }
                }

                namespace Root.Features
                {
                    public static class Widgets
                    {
                        // 'Models.Widget' / 'Models.Box<int>' resolve lexically to 'Root.Models.*'
                        // through the shared 'Root' parent, but the using-less generated RenderBody
                        // cannot resolve the relative 'Models' path, so it must be fully qualified on
                        // expansion while any written type arguments are preserved.
                        [Composable]
                        public static View Show() =>
                            Text(Models.Widget.Label + typeof(Models.Widget).Name + Models.Box<int>.Describe);
                    }
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;
                using Root.Features;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets.Show();
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var generated = Assert.Single(result.GeneratedSources).SourceText.ToString();

        // The static-member access, the typeof type reference, and the generic type reference — all
        // written under the relative 'Models' path — are fully qualified to 'global::Root.Models.*',
        // and the generic type argument survives, so expansion into the global namespace compiles.
        Assert.Contains("global::Root.Models.Widget.Label", generated);
        Assert.Contains("typeof(global::Root.Models.Widget)", generated);
        Assert.Contains("global::Root.Models.Box<int>.Describe", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    // -----------------------------------------------------------------------
    // Component Body normalization diagnostics surface as BC1002
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_ComponentBodyWithUnnormalizableExtensionReceiver_ReportsBC1002AndEmitsNoSource()
    {
        const string source = """
            using BlazorCompose;
            using static BlazorCompose.UI;
            using System.Collections.Generic;
            using System.Linq;

            public partial class Counter : ComposeComponentBase
            {
                private IEnumerable<string> _items = new List<string> { "a" };

                // A null-conditional extension receiver cannot be rewritten to a static call without
                // changing short-circuit semantics, so Body normalization reports BC1002.
                protected override View Body => Text(_items?.First());
            }
            """;

        var result = CompilationTestHost.RunGenerator(source);

        // The Body path surfaces exactly one BC1002 (previously the diagnostic was discarded).
        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        Assert.Contains("cannot be normalized", diagnostic.GetMessage(CultureInfo.InvariantCulture));

        // Emission is suppressed rather than producing a broken RenderBody.
        Assert.Empty(result.GeneratedSources);

        // The only remaining consequence is the expected abstract-member gap (CS0534); there is no
        // secondary generator error from broken generated source.
        var error = Assert.Single(
            result.OutputCompilation.GetDiagnostics(),
            static d => d.Severity == DiagnosticSeverity.Error);
        Assert.Equal("CS0534", error.Id);
    }

    // -----------------------------------------------------------------------
    // Composables in generic containing types are rejected (would leak 'T')
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_ComposableInGenericContainingTypeWithTypeParameter_ReportsBC1002AndEmitsNoSource()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public class Widgets<T>
                {
                    // A composable declared in a generic containing type would leak the unbound type
                    // parameter 'T' — here through the 'T value' parameter — into the using-less
                    // generated component, so the declaration is rejected up front.
                    [Composable]
                    public static View Show(T value) => Text(value!.ToString());
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets<int>.Show(5);
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Show", message);
        Assert.Contains("containing type must be non-generic", message);

        // The rejected composable never expands, so no broken component source (which would leak the
        // unbound 'T') is produced.
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ComposableInGenericContainingTypeReferencingTypeParameter_ReportsBC1002AndEmitsNoSource()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public class Widgets<T>
                {
                    // Even a parameterless composable leaks 'T' through its body (typeof(T)); the
                    // generic containing type is rejected regardless of the parameter list.
                    [Composable]
                    public static View Show() => Text(typeof(T).Name);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Widgets<int>.Show();
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Show", message);
        Assert.Contains("containing type must be non-generic", message);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_ComposableInGenericEnclosingType_ReportsBC1002AndEmitsNoSource()
    {
        var result = CompilationTestHost.RunGenerator(
            ("Widgets.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public class Outer<T>
                {
                    // The composable's immediate containing type is non-generic, but an *enclosing*
                    // containing type is generic, so 'T' would still leak: the declaration is rejected.
                    public static class Inner
                    {
                        [Composable]
                        public static View Show() => Text(typeof(T).Name);
                    }
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Outer<int>.Inner.Show();
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Show", message);
        Assert.Contains("containing type must be non-generic", message);
        Assert.Empty(result.GeneratedSources);
    }

    // -----------------------------------------------------------------------
    // Access requirements are keyed on the referenced member's declaring type,
    // not the composable definition's containing type
    // -----------------------------------------------------------------------

    [Fact]
    public void Generator_ProtectedBaseMemberReferencedFromHelperType_ExpandsIntoDerivedComponent()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract partial class WidgetBase : ComposeComponentBase
                {
                    protected static string Prefix() => "P:";
                }
                """),
            ("Helper.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                // The composable lives in a *different* type than the one declaring the protected
                // member.  It can name 'Prefix' because Helper derives from WidgetBase, so the access
                // requirement must be validated against the member's declaring type (WidgetBase) — not
                // the composable's containing type (Helper).
                public abstract partial class Helper : WidgetBase
                {
                    [Composable]
                    public static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public partial class Counter : WidgetBase
                {
                    protected override View Body => Helper.Label("x");
                }
                """));

        Assert.DoesNotContain(result.Diagnostics, static d => d.Id == "BC1002");
        var counter = Assert.Single(
            result.GeneratedSources, static s => s.HintName.Contains("Counter"));
        var generated = counter.SourceText.ToString();
        Assert.Contains("global::WidgetBase.Prefix()", generated);
        Assert.DoesNotContain("Label(", generated);
        CompilationTestHost.AssertOutputCompiles(result);
    }

    [Fact]
    public void Generator_ProtectedBaseMemberReferencedFromHelperTypeIntoUnrelatedComponent_ReportsBC1002()
    {
        var result = CompilationTestHost.RunGenerator(
            ("WidgetBase.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract partial class WidgetBase : ComposeComponentBase
                {
                    protected static string Prefix() => "P:";
                }
                """),
            ("Helper.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                public abstract partial class Helper : WidgetBase
                {
                    [Composable]
                    public static View Label(string value) => Text(Prefix() + value);
                }
                """),
            ("Counter.cs", """
                using BlazorCompose;
                using static BlazorCompose.UI;

                // Counter does not derive from WidgetBase, so it cannot legally name the protected
                // 'Prefix'; the requirement (keyed on WidgetBase) is correctly unsatisfied here.
                public partial class Counter : ComposeComponentBase
                {
                    protected override View Body => Helper.Label("x");
                }
                """));

        var diagnostic = Assert.Single(result.Diagnostics, static d => d.Id == "BC1002");
        var message = diagnostic.GetMessage(CultureInfo.InvariantCulture);
        Assert.Contains("Prefix", message);
        Assert.Contains("not accessible", message);
        Assert.Empty(result.GeneratedSources);
    }

    /// <summary>
    /// Asserts that both <paramref name="first"/> and <paramref name="second"/> occur in
    /// <paramref name="source"/> and that <paramref name="first"/> appears before <paramref name="second"/>.
    /// </summary>
    private static void AssertAppearsBefore(string source, string first, string second)
    {
        var firstIndex = source.IndexOf(first, System.StringComparison.Ordinal);
        var secondIndex = source.IndexOf(second, System.StringComparison.Ordinal);

        Assert.True(firstIndex >= 0, $"Expected to find '{first}' in generated source.");
        Assert.True(secondIndex >= 0, $"Expected to find '{second}' in generated source.");
        Assert.True(
            firstIndex < secondIndex,
            $"Expected '{first}' to appear before '{second}' in generated source.");
    }
}
