using System;
using System.Text;
using BlazorCompose.Compiler.Generation;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCompose.Compiler;

/// <summary>Emits a <c>RenderBody</c> override into the generated partial class.</summary>
internal static class RenderBodyEmitter
{
    private const string RtbType =
        "global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private const string EventCallbackFactory =
        "global::Microsoft.AspNetCore.Components.EventCallback.Factory";

    public static SourceText Emit(ComponentModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0219");
        sb.AppendLine();

        if (model.Namespace is { } ns)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    protected override void RenderBody({RtbType} __builder)");
        sb.AppendLine("    {");

        EmitNode(sb, model.RootNode, startSeq: 0, indent: "        ");

        sb.AppendLine("    }");
        sb.Append('}');

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    // ---------------------------------------------------------------------------
    // Node emission — returns the next available sequence number
    // ---------------------------------------------------------------------------

    private static int EmitNode(StringBuilder sb, RenderNode node, int startSeq, string indent)
    {
        switch (node)
        {
            case TextNode text:
                return EmitText(sb, text, startSeq, indent);
            case ButtonNode button:
                return EmitButton(sb, button, startSeq, indent);
            case VStackNode vstack:
                return EmitVStack(sb, vstack, startSeq, indent);
            case IfNode ifNode:
                return EmitIf(sb, ifNode, startSeq, indent);
            case ExpansionNode expansion:
                foreach (var local in expansion.Locals)
                {
                    sb.AppendLine(
                        $"{indent}{local.TypeName} {local.Name} = {local.Initializer.ToCode()};");
                }

                return EmitNode(sb, expansion.Body, startSeq, indent);
            default:
                throw new NotSupportedException(
                    $"Emission for '{node.GetType().Name}' is not yet implemented.");
        }
    }

    private static int EmitText(StringBuilder sb, TextNode node, int seq, string indent)
    {
        sb.AppendLine($"{indent}__builder.OpenElement({seq}, \"span\");");
        sb.AppendLine($"{indent}__builder.AddContent({seq + 1}, {node.ContentExpression.ToCode()});");
        sb.AppendLine($"{indent}__builder.CloseElement();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitButton(StringBuilder sb, ButtonNode node, int seq, string indent)
    {
        sb.AppendLine($"{indent}__builder.OpenElement({seq}, \"button\");");
        sb.AppendLine(
            $"{indent}__builder.AddAttribute({seq + 1}, \"onclick\", " +
            $"{EventCallbackFactory}.Create(this, {node.HandlerExpression.ToCode()}));");
        sb.AppendLine($"{indent}__builder.AddContent({seq + 2}, {node.LabelExpression.ToCode()});");
        sb.AppendLine($"{indent}__builder.CloseElement();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitVStack(StringBuilder sb, VStackNode node, int seq, string indent)
    {
        sb.AppendLine($"{indent}__builder.OpenElement({seq}, \"div\");");
        int nextSeq = seq + 1;
        foreach (var child in node.Children)
            nextSeq = EmitNode(sb, child, nextSeq, indent);
        sb.AppendLine($"{indent}__builder.CloseElement();");
        return nextSeq;
    }

    private static int EmitIf(StringBuilder sb, IfNode node, int seq, string indent)
    {
        // seq is consumed by OpenRegion.
        // then  branch occupies [seq+1, seq+1+W(then)).
        // else  branch occupies [seq+1+W(then), seq+1+W(then)+W(else)).
        // The total reservation equals SequenceAllocator.Width(node) so that sibling nodes
        // always receive a sequence that is independent of which branch executes at runtime.
        int thenStart = seq + 1;

        sb.AppendLine($"{indent}__builder.OpenRegion({seq});");
        sb.AppendLine($"{indent}if ({node.ConditionExpression.ToCode()})");
        sb.AppendLine($"{indent}{{");
        int afterThen = EmitNode(sb, node.Then, thenStart, indent + "    ");
        sb.AppendLine($"{indent}}}");

        if (node.Otherwise is not null)
        {
            // afterThen == seq+1+Width(then) which is exactly where the else range begins.
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            EmitNode(sb, node.Otherwise, afterThen, indent + "    ");
            sb.AppendLine($"{indent}}}");
        }

        sb.AppendLine($"{indent}__builder.CloseRegion();");

        return seq + SequenceAllocator.Width(node);
    }
}
