using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCompose.Compiler;

/// <summary>Emits a <c>RenderBody</c> override into the generated partial class.</summary>
internal static class RenderBodyEmitter
{
    public static SourceText Emit(ComponentModel model)
    {
        var body = model.Namespace is { } ns
            ? $$"""
              // <auto-generated/>
              #nullable enable

              namespace {{ns}};

              partial class {{model.ClassName}}
              {
                  protected override void RenderBody(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
                  {
                  }
              }
              """
            : $$"""
              // <auto-generated/>
              #nullable enable

              partial class {{model.ClassName}}
              {
                  protected override void RenderBody(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
                  {
                  }
              }
              """;

        return SourceText.From(body, Encoding.UTF8);
    }
}
