using System;
using System.Diagnostics;
using System.Text;
using BlazorCompose.Compiler.Generation;
using Microsoft.CodeAnalysis.Text;

namespace BlazorCompose.Compiler;

/// <summary>Emits a <c>RenderBody</c> override into the generated partial class.</summary>
internal static class RenderBodyEmitter
{
    private const string RtbType =
        "global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder";

    private const string EventCallbackFactory =
        "global::Microsoft.AspNetCore.Components.EventCallback.Factory";

    public static SourceText Emit(ComponentModel model)
    {
        var writer = new IndentedWriter();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine("#pragma warning disable CS0219");
        writer.AppendLine();

        if (model.Namespace is { } ns)
        {
            writer.AppendLine($"namespace {ns};");
            writer.AppendLine();
        }

        writer.AppendLine($"partial class {model.ClassName}");
        writer.AppendLine("{");
        writer.Indent++;
        writer.AppendLine($"protected override void RenderBody({RtbType} __builder)");
        writer.AppendLine("{");
        writer.Indent++;

        EmitNode(writer, model.RootNode, startSeq: 0);

        writer.Indent--;
        writer.AppendLine("}");
        writer.Indent--;
        writer.Append("}");

        return SourceText.From(writer.ToString(), Encoding.UTF8);
    }

    // ---------------------------------------------------------------------------
    // Node emission — returns the next available sequence number
    // ---------------------------------------------------------------------------

    /// <param name="key">
    /// When non-<see langword="null"/>, a key expression to apply to this node's root element/component
    /// frame via <c>SetKey</c> immediately after it opens. Supplied only by <see cref="EmitForEach"/> for
    /// the loop content root; the key is consumed by the first element/component and never propagated to
    /// children. Region-rooted nodes (<see cref="IfNode"/>, <see cref="ForEachNode"/>) never receive a
    /// non-<see langword="null"/> key because BC3003 blocks region-rooted content from reaching emission.
    /// </param>
    private static int EmitNode(IndentedWriter writer, RenderNode node, int startSeq, string? key = null) =>
        node switch
        {
            TextNode text => EmitText(writer, text, startSeq, key),
            ButtonNode button => EmitButton(writer, button, startSeq, key),
            VStackNode vstack => EmitVStack(writer, vstack, startSeq, key),
            IfNode ifNode => EmitIf(writer, ifNode, startSeq, key),
            ExpansionNode expansion => EmitExpansion(writer, expansion, startSeq, key),
            ForEachNode forEach => EmitForEach(writer, forEach, startSeq, key),
            ComponentNode component => EmitComponent(writer, component, startSeq, key),
            _ => throw new NotSupportedException(
                $"Emission for '{node.GetType().Name}' is not yet implemented."),
        };

    private static int EmitText(IndentedWriter writer, TextNode node, int seq, string? key = null)
    {
        writer.AppendLine($"__builder.OpenElement({seq}, \"span\");");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        writer.AppendLine($"__builder.AddContent({seq + 1}, {node.ContentExpression.ToCode()});");
        writer.AppendLine("__builder.CloseElement();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitButton(IndentedWriter writer, ButtonNode node, int seq, string? key = null)
    {
        writer.AppendLine($"__builder.OpenElement({seq}, \"button\");");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        writer.AppendLine(
            $"__builder.AddAttribute({seq + 1}, \"onclick\", " +
            $"{EventCallbackFactory}.Create(this, {node.HandlerExpression.ToCode()}));");
        writer.AppendLine($"__builder.AddContent({seq + 2}, {node.LabelExpression.ToCode()});");
        writer.AppendLine("__builder.CloseElement();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitVStack(IndentedWriter writer, VStackNode node, int seq, string? key = null)
    {
        writer.AppendLine($"__builder.OpenElement({seq}, \"div\");");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int nextSeq = seq + 1;
        foreach (var child in node.Children)
            nextSeq = EmitNode(writer, child, nextSeq);
        writer.AppendLine("__builder.CloseElement();");
        return nextSeq;
    }

    private static int EmitIf(IndentedWriter writer, IfNode node, int seq, string? key = null)
    {
        // Region-rooted nodes never carry a threaded key: BC3003 blocks region-rooted content from
        // reaching emission, so a non-null key here would mean a keyable node was wired to this branch
        // without updating that contract. Fail fast in tests instead of silently dropping SetKey.
        Debug.Assert(key is null, $"{nameof(EmitIf)} does not support a threaded key; SetKey would be silently dropped.");

        // seq is consumed by OpenRegion.
        // then  branch occupies [seq+1, seq+1+W(then)).
        // else  branch occupies [seq+1+W(then), seq+1+W(then)+W(else)).
        // The total reservation equals SequenceAllocator.Width(node) so that sibling nodes
        // always receive a sequence that is independent of which branch executes at runtime.
        int thenStart = seq + 1;

        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"if ({node.ConditionExpression.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        int afterThen = EmitNode(writer, node.Then, thenStart);
        writer.Indent--;
        writer.AppendLine("}");

        if (node.Otherwise is not null)
        {
            // afterThen == seq+1+Width(then) which is exactly where the else range begins.
            writer.AppendLine("else");
            writer.AppendLine("{");
            writer.Indent++;
            EmitNode(writer, node.Otherwise, afterThen);
            writer.Indent--;
            writer.AppendLine("}");
        }

        writer.AppendLine("__builder.CloseRegion();");

        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitForEach(IndentedWriter writer, ForEachNode node, int seq, string? key = null)
    {
        // Region-rooted nodes never carry a threaded key: BC3003 blocks region-rooted content from
        // reaching emission, so a non-null key here would mean a keyable node was wired to this branch
        // without updating that contract. Fail fast in tests instead of silently dropping SetKey.
        Debug.Assert(key is null, $"{nameof(EmitForEach)} does not support a threaded key; SetKey would be silently dropped.");

        // seq is consumed by OpenRegion. The content template occupies [seq+1, seq+1+W(content)) and
        // those sequence numbers are re-emitted every iteration; SetKey carries per-item identity.
        writer.AppendLine($"__builder.OpenRegion({seq});");
        writer.AppendLine($"foreach (var {node.LoopVariableName} in {node.Source.ToCode()})");
        writer.AppendLine("{");
        writer.Indent++;
        // The key is threaded into the content's root element/component so SetKey is emitted
        // immediately after that frame opens — never after OpenRegion (see BC3003).
        EmitNode(writer, node.Content, seq + 1, node.Key.ToCode());
        writer.Indent--;
        writer.AppendLine("}");
        writer.AppendLine("__builder.CloseRegion();");
        return seq + SequenceAllocator.Width(node);
    }

    private static int EmitExpansion(IndentedWriter writer, ExpansionNode node, int startSeq, string? key = null)
    {
        foreach (var local in node.Locals)
        {
            writer.AppendLine(
                $"{local.TypeName} {local.Name} = {local.Initializer.ToCode()};");
        }

        // Forward the key to the composable body's root element/component.
        return EmitNode(writer, node.Body, startSeq, key);
    }

    private static int EmitComponent(IndentedWriter writer, ComponentNode node, int seq, string? key = null)
    {
        // TypeName already carries the global:: prefix (fully qualified format).
        writer.AppendLine($"__builder.OpenComponent<{node.TypeName}>({seq});");
        if (key is not null)
            writer.AppendLine($"__builder.SetKey({key});");
        int next = seq + 1;
        foreach (var parameter in node.Parameters)
        {
            writer.AppendLine(
                $"__builder.AddComponentParameter({next}, \"{parameter.Name}\", {parameter.Value.ToCode()});");
            next++;
        }
        writer.AppendLine("__builder.CloseComponent();");
        return seq + SequenceAllocator.Width(node);
    }

    /// <summary>
    /// Minimal indent-aware wrapper over a <see cref="StringBuilder"/>.  Line endings come from
    /// <see cref="StringBuilder.AppendLine()"/> (<see cref="Environment.NewLine"/>) so generated
    /// output stays byte-identical to the previous manual indent threading.
    /// </summary>
    /// <remarks>
    /// <see cref="System.CodeDom.Compiler.IndentedTextWriter"/> is deliberately not used: System.CodeDom
    /// is outside the netstandard2.0 shared framework and is not bundled with the packaged analyzer, so
    /// referencing it would risk a <see cref="System.IO.FileNotFoundException"/> at analyzer load time.
    /// </remarks>
    private sealed class IndentedWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new();

        /// <summary>The current indentation depth, in units of four spaces.</summary>
        public int Indent { get; set; }

        /// <summary>Appends a blank line, without leading indentation.</summary>
        public void AppendLine() => _sb.AppendLine();

        /// <summary>Appends the current indentation followed by <paramref name="text"/> and a line break.</summary>
        public void AppendLine(string text)
        {
            AppendIndent();
            _sb.AppendLine(text);
        }

        /// <summary>Appends the current indentation followed by <paramref name="text"/>, without a line break.</summary>
        public void Append(string text)
        {
            AppendIndent();
            _sb.Append(text);
        }

        public override string ToString() => _sb.ToString();

        private void AppendIndent()
        {
            for (int i = 0; i < Indent; i++)
                _sb.Append(IndentUnit);
        }
    }
}
